%%writefile app.py
import streamlit as st
import tensorflow as tf
import numpy as np
import pickle
import google.generativeai as genai
from tensorflow.keras.preprocessing.sequence import pad_sequences
import json
import re
import plotly.graph_objects as go
from fpdf import FPDF
import base64

# --- 1. CONFIGURATION (FIX: FORCE EXPANDED) ---
st.set_page_config(
    page_title="VentureVision",
    page_icon="🔥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 🔴 PASTE YOUR API KEY HERE
GOOGLE_API_KEY = "AIzaSyDohh2u2MSnxQnwLpa_g0QkqJbBE8q1DDY"

try:
    genai.configure(api_key=GOOGLE_API_KEY)
    agent_model = genai.GenerativeModel('gemini-2.0-flash')
except:
    pass

# --- 2. LOAD BRAIN ---
@st.cache_resource
def load_brain():
    try:
        model = tf.keras.models.load_model('venture_model.h5')
        with open('tokenizer.pickle', 'rb') as h: tokenizer = pickle.load(h)
        with open('scaler.pickle', 'rb') as h: scaler = pickle.load(h)
        return model, tokenizer, scaler
    except:
        return None, None, None

model, tokenizer, scaler = load_brain()

# --- 3. DYNAMIC DATA ---
CURRENCY_MAP = {"USA": "$", "Europe": "€", "UK": "£", "India": "₹", "Japan": "¥", "UAE": "AED"}
INDUSTRY_TIPS = {
    "Technology": "Focus on IP & Scalability.", "Retail": "Margins are thin; brand is key.",
    "Food & Beverage": "Location is 80% of success.", "Health": "Regulations will slow you down.",
    "Service": "Hard to scale without people.", "Real Estate": "Capital intensive market."
}

# --- 4. PDF GENERATOR ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'VentureVision Analysis Report', 0, 1, 'C')
        self.ln(10)
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by VentureVision', 0, 0, 'C')

def clean_text_strict(text):
    if not isinstance(text, str): return str(text)
    replacements = {
        "₹": "Rs. ", "€": "EUR ", "£": "GBP ", "¥": "JPY ",
        "⚠️": "[!]", "✅": "[OK]", "🔥": "", "🚀": "", "🔻": "", "🏢": ""
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'ignore').decode('latin-1')

def create_pdf(desc, budget, score, report, currency_symbol, budget_verdict):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    safe_verdict = clean_text_strict(report.get('verdict', 'N/A'))
    safe_summary = clean_text_strict(report.get('detailed_analysis', 'N/A'))
    safe_budget_msg = clean_text_strict(budget_verdict)

    curr_text = currency_symbol
    if currency_symbol == "₹": curr_text = "Rs."
    elif currency_symbol == "€": curr_text = "EUR"
    elif currency_symbol == "£": curr_text = "GBP"

    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Verdict: {safe_verdict}", 0, 1)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Score: {score:.1f}% | Capital: {curr_text} {budget:,}", 0, 1)
    pdf.cell(0, 10, f"Budget Check: {safe_budget_msg}", 0, 1)
    pdf.ln(5)

    pdf.multi_cell(0, 10, safe_summary)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Strategic Plan", 0, 1)
    pdf.set_font("Arial", size=11)

    for step in report.get('action_plan', []):
        safe_step = clean_text_strict(step)
        pdf.multi_cell(0, 8, f"- {safe_step}")

    return pdf.output(dest='S').encode('latin-1', 'replace')

# --- 5. LOGIC & VISUALS ---
def create_dashboard_donut(score):
    colors = ['#FF2E63', '#252A34'] if score < 50 else ['#08D9D6', '#252A34']
    fig = go.Figure(data=[go.Pie(
        labels=['Val', 'Rem'], values=[score, 100-score], hole=.75,
        marker=dict(colors=colors, line=dict(color='#1A1A1D', width=0)),
        textinfo='none', sort=False, direction='clockwise'
    )])
    fig.update_layout(
        showlegend=False, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
        margin=dict(t=10, b=10, l=10, r=10), height=160,
        annotations=[dict(text=f"{int(score)}%", x=0.5, y=0.5, font_size=32, font_color="#FFFFFF", showarrow=False, font_family="Arial Black")]
    )
    return fig

def sanity_check(desc, budget, raw_score):
    desc_lower = desc.lower()
    budget_msg = "✅ HEALTHY"
    limit_high = 500000000
    limit_low = 1000

    if any(x in desc_lower for x in ['bakery','food','cafe','shop','store']):
        limit_high = 50000000
        limit_low = 50000

    if budget > limit_high: return max(raw_score - 80, 5.0), "OVERCAPITALIZED", f"⚠️ EXCESSIVE: {budget:,} is inefficient."
    if budget < limit_low: return max(raw_score - 50, 5.0), None, f"⚠️ UNDERFUNDED: {budget:,} is too low."
    return raw_score, None, f"✅ HEALTHY: Budget is standard."

def run_agent(desc, budget, score, warning, country, currency):
    context = f"CRITICAL: User allocated {currency}{budget} which is unrealistic." if warning else ""
    prompt = f"""Act as a Senior VC in {country}. Project: "{desc}" ({currency}{budget}). Score: {score:.1f}%. {context}.
    Return valid JSON. Be DETAILED.
    {{
        "verdict": "3-Word Punchy Title",
        "detailed_analysis": "3-4 sentences explaining the score, market fit, and budget reality.",
        "pros": ["Strength 1 (Reason)", "Strength 2 (Reason)"],
        "cons": ["Risk 1 (Reason)", "Risk 2 (Reason)"],
        "competitors": ["Co 1", "Co 2"],
        "action_plan": ["Step 1", "Step 2", "Step 3"]
    }}"""
    try:
        res = agent_model.generate_content(prompt)
        text = res.text.replace('```json', '').replace('```', '').strip()
        match = re.search(r'\{.*\}', text, re.DOTALL)
        return json.loads(match.group(0)) if match else json.loads(text)
    except: return {"verdict": "Error", "detailed_analysis": "N/A", "pros": ["N/A"], "cons": ["N/A"], "competitors": [], "action_plan": []}

# --- 6. DARK FLOATING WINDOW CSS (FIXED SIDEBAR BUTTON) ---
st.markdown("""
    <style>
    :root { --bg: #000000; --card: #1c1c21; --sidebar: #121214; --accent: #ff4757; --text: #ffffff; }

    .stApp {
        background-color: var(--bg);
        background-image: radial-gradient(circle at 50% 50%, #1a1a1a 0%, #000000 100%);
    }
    .block-container {
        background-color: #121214;
        border-radius: 20px;
        padding: 3rem !important;
        margin-top: 2rem;
        margin-bottom: 2rem;
        box-shadow: 0 0 50px rgba(255, 71, 87, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.05);
        max-width: 95% !important;
    }

    [data-testid="stSidebar"] {
        background-color: var(--sidebar);
        border-right: 1px solid #222;
        margin-top: 2rem;
    }

    /* --- FIX: VISIBLE SIDEBAR TOGGLE --- */
    /* This forces the toggle button to be Neon Red and visible */
    [data-testid="stSidebarCollapsedControl"] {
        color: #ff4757 !important;
        background-color: #1e1e24 !important;
        border: 1px solid #333;
        border-radius: 8px;
        z-index: 100000;
        display: block !important;
    }

    /* HEADER VISIBILITY FIX */
    header {visibility: visible !important; background: transparent !important;}
    [data-testid="stHeader"] { background: transparent !important; }

    html, body, p, label, li, h1, h2, h3, h4 { color: var(--text) !important; font-family: 'Segoe UI', sans-serif; }
    h1 {
        background: -webkit-linear-gradient(0deg, #ff4757, #ff6b81);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 3.5rem !important;
        font-weight: 800 !important;
        margin-bottom: 0px !important;
    }

    .stTextInput input, .stTextArea textarea, .stNumberInput input, .stSelectbox div[data-baseweb="select"] {
        background-color: #1c1c21 !important;
        color: white !important;
        border: 1px solid #333 !important;
        border-radius: 12px;
    }

    .bento-card {
        background: linear-gradient(145deg, #1c1c21 0%, #151518 100%);
        border-radius: 16px;
        padding: 25px;
        border: 1px solid rgba(255,255,255,0.05);
        box-shadow: 0 10px 30px rgba(0,0,0,0.3);
        margin-bottom: 20px;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    .bento-card:hover { transform: translateY(-2px); border-color: var(--accent); transition: 0.3s; }

    .stButton>button {
        background: linear-gradient(90deg, #ff4757 0%, #ff6b81 100%);
        color: white; border: none; border-radius: 12px; padding: 15px; width: 100%;
        font-weight: bold; font-size: 1.1rem;
        box-shadow: 0 4px 15px rgba(255, 71, 87, 0.3);
    }

    .pro-list li { color: #2ed573 !important; margin-bottom: 12px; }
    .con-list li { color: #ff4757 !important; margin-bottom: 12px; }
    </style>
""", unsafe_allow_html=True)

# --- 7. LAYOUT ---
with st.sidebar:
    st.header("⚙️ SETTINGS")
    country = st.selectbox("Target Region", list(CURRENCY_MAP.keys()))
    currency = CURRENCY_MAP[country]
    industry = st.selectbox("Industry Sector", list(INDUSTRY_TIPS.keys()))
    st.info(INDUSTRY_TIPS[industry])
    st.markdown("---")

# HEADER
c1, c2 = st.columns([3, 1])
with c1:
    st.title("VENTURE VISION")
    st.markdown(f"**Analytics Dashboard • {industry} • {country}**")
with c2:
    st.markdown('<div style="height: 20px;"></div>', unsafe_allow_html=True)

desc = st.text_area("", height=70, placeholder="Describe your startup concept here...")
c1, c2, c3 = st.columns([1, 1, 2])
with c1: budget = st.number_input(f"Capital ({currency})", value=50000, step=5000)
with c2: comp_est = st.slider("Saturation", 0, 50, 20)
with c3:
    st.markdown('<div style="height: 28px;"></div>', unsafe_allow_html=True)
    run_btn = st.button("RUN ANALYSIS 🚀")

if run_btn and desc:
    if model:
        with st.spinner("Processing..."):
            # 1. CURRENCY CONVERSION (Fix 0% bug)
            usd_budget = budget * 0.012 if currency == "₹" else budget

            # 2. MODEL PREDICTION
            seq = tokenizer.texts_to_sequences([desc])
            padded = pad_sequences(seq, maxlen=25, padding='post', truncating='post')
            scaled = scaler.transform([[usd_budget, comp_est]])
            raw_score = float(model.predict([padded, scaled])[0][0]) * 100

            # 3. SANITY & AGENT
            final_score, warning, budget_msg = sanity_check(desc, usd_budget, raw_score)
            report = run_agent(desc, budget, final_score, warning, country, currency)

        # ROW 1
        g1, g2, g3 = st.columns([1, 1.5, 1.5])
        with g1:
            st.markdown('<div class="bento-card" style="text-align:center; padding-top:10px;">', unsafe_allow_html=True)
            st.plotly_chart(create_dashboard_donut(final_score), use_container_width=True)
            st.markdown('<div style="color:#ccc; font-size:0.8rem; margin-top:-10px;">VIABILITY</div></div>', unsafe_allow_html=True)
        with g2:
            st.markdown(f"""<div class="bento-card"><h3>VERDICT: {report['verdict']}</h3><p style="font-size:1rem; color:#ddd;">{report['detailed_analysis']}</p></div>""", unsafe_allow_html=True)
        with g3:
            risk_color = "#ff4757" if final_score < 50 else "#2ed573"
            risk_text = "HIGH" if final_score < 50 else "LOW"
            # PDF GEN
            pdf = create_pdf(desc, budget, final_score, report, currency, budget_msg)
            b64 = base64.b64encode(pdf).decode()
            st.markdown(f"""
            <div class="bento-card" style="text-align:center;">
                <div style="font-size:0.9rem; color:#ccc; margin-bottom:5px;">BUDGET HEALTH</div>
                <div style="font-size:1.1rem; font-weight:bold; color:{'#2ed573' if 'HEALTHY' in budget_msg else '#ff4757'};">{budget_msg.split(':')[0]}</div>
                <div style="margin-top:15px; border-top:1px solid #444; padding-top:10px;">
                    <div style="font-size:0.8rem; color:#ccc;">RISK LEVEL: <span style="color:{risk_color}; font-size:1.2rem; font-weight:bold;">{risk_text}</span></div>
                </div>
                <a href="data:application/octet-stream;base64,{b64}" download="VentureReport.pdf" style="text-decoration:none;">
                    <div style="background: linear-gradient(90deg, {risk_color}, #2f3542); padding:8px; border-radius:6px; color:white; font-size:0.8rem; font-weight:bold; margin-top: 10px;">📥 PDF</div>
                </a>
            </div>""", unsafe_allow_html=True)

        # ROW 2 & 3
        c1, c2 = st.columns(2)
        with c1:
            st.markdown('<div class="bento-card"><h3>🔥 STRENGTHS</h3><ul class="pro-list">', unsafe_allow_html=True)
            for p in report['pros']: st.markdown(f"<li>{p}</li>", unsafe_allow_html=True)
            st.markdown('</ul></div>', unsafe_allow_html=True)
        with c2:
            st.markdown('<div class="bento-card"><h3>🔻 RISKS</h3><ul class="con-list">', unsafe_allow_html=True)
            for c in report['cons']: st.markdown(f"<li>{c}</li>", unsafe_allow_html=True)
            st.markdown('</ul></div>', unsafe_allow_html=True)

        d1, d2 = st.columns(2)
        with d1:
            st.markdown(f'<div class="bento-card"><h3>🏢 COMPETITORS ({country})</h3><ul>', unsafe_allow_html=True)
            for c in report['competitors']: st.markdown(f"<li>{c}</li>", unsafe_allow_html=True)
            st.markdown('</ul></div>', unsafe_allow_html=True)
        with d2:
            st.markdown('<div class="bento-card"><h3>🚀 ROADMAP</h3><ul>', unsafe_allow_html=True)
            for i, s in enumerate(report['action_plan'], 1): st.markdown(f"<li><strong>{i}.</strong> {s}</li>", unsafe_allow_html=True)
            st.markdown('</ul></div>', unsafe_allow_html=True)
